workflows:
  android-build:
    name: Build Android Debug APK
    max_build_duration: 60
    environment:
      vars:
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Checkout repository
        script: |
          git clone https://github.com/manusccv-ai/ElectraApp.git
          cd ElectraApp
      - name: Install Android SDK and Build Tools
        script: |
          sudo sdkmanager "build-tools;33.0.2" "platforms;android-33" "ndk;23.1.7779620"
      - name: Install Gradle if missing
        script: |
          if ! command -v gradle &> /dev/null
          then
              echo "Gradle not found, installing..."
              wget https://services.gradle.org/distributions/gradle-8.4.1-bin.zip -O gradle.zip
              unzip gradle.zip
              export PATH=$PWD/gradle-8.4.1/bin:$PATH
          fi
      - name: Build APK
        script: |
          cd ElectraApp
          gradle assembleDebug || { echo "Build failed :|"; exit 1; }
    artifacts:
      - build/app/outputs/**/*.apk
